language: python
python:
  - "2.7"
#  - "3.4"
# From https://github.com/Myzhar/RoboController-ROS/blob/master/.travis.yml 
cache:
  - apt
before_install: # Use this to prepare the system to install prerequisites or dependencies
  # Define some config vars
  - export ROS_DISTRO=hydro
  #- export CI_SOURCE_PATH=$(pwd)
  #- export REPOSITORY_NAME=${PWD##*/}
  #- echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq ros-hydro-catkin ros-hydro-desktop
  #- sudo apt-get install -y -qq libmodbus-dev
  # MongoDB hack - I don't fully understand this but its for moveit_warehouse
  #- sudo apt-get remove -y mongodb mongodb-10gen
  #- sudo apt-get install -y mongodb-clients mongodb-server -o Dpkg::Options::="--force-confdef" # default actions
  # Setup rosdep
  - sudo rosdep init
  - rosdep update
install: # Use this to install any prerequisites or dependencies necessary to run your build
  # Create workspace
  - mkdir -p ~/ros/catkin_ws/src
  - cd ~/ros/catkin_ws/src
  #- wstool init .
  # Download non-debian stuff
  - git clone https://github.com/UC3MSocialRobots/rospy_utils.git
  #- wstool update
  # Delete the moveit.rosinstall version of this repo and use the one of the branch we are testing
  #- rm -rf $REPOSITORY_NAME
  #- ln -s $CI_SOURCE_PATH . # Link the repo we are testing to the new workspace
  #- cd ../
  # Install dependencies for source repos
  # - rosdep install --from-paths src --ignore-src --rosdistro $ROS_DISTRO -y
before_script: # Use this to prepare your build for testing e.g. copy database configurations, environment variables, etc.
  - source /opt/ros/$ROS_DISTRO/setup.bash
###################################
# command to install dependencies
#install: "pip install -r requirements.txt"
# command to run tests
script: 
  #- cd ~/ros/catkin_ws/src/rospy_utils
  - nosetests
